# ELK Stack image with customization

FROM willdurand/elk

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-23

COPY logstash-logspout.conf /etc/logstash/logstash-logspout.conf