# Logspout with Logstash image with customization

# https://github.com/looplab/logspout-logstash
# https://github.com/gliderlabs/logspout/tree/master/custom
# builds with modules.go in project root (not here)
# test: nc elk 5000 < /dev/null; echo $? # return 0 if working

FROM gliderlabs/logspout:master

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-05